apiVersion: k8s.kiwigrid.com/v1beta1
kind: Keycloak
metadata:
  name: keycloak-test1
  # namespace: keycloak-test1
  #^ keycloak cr is not namespaced (?)
spec:
  url: https://keycloak-test1.codeformuenster.org/auth
  realm: master
  clientId: admin-cli
  username: admin
  passwordSecretNamespace: keycloak-test1
  passwordSecretName: keycloak-http
  passwordSecretKey: password