apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
commonLabels:
  app.kubernetes.io/name: kube-router
  app.kubernetes.io/part-of: kube-router

resources:
- ./kubeadm-kuberouter-all-features-hostport.yaml

images:
- name: docker.io/cloudnativelabs/kube-router
  newTag: v0.3.2
- name: busybox
  newTag: "1.31"

patchesStrategicMerge:
- ./rollingUpgrade-patch.yaml