apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elasticsearch-test
commonLabels:
  app.kubernetes.io/part-of: kibana

resources:
- ./helm/output/kibana/templates/deployment.yaml
- ./helm/output/kibana/templates/service.yaml
- ./helm/output/kibana/templates/configmap.yaml

images:
- name: docker.elastic.co/kibana/kibana-oss
  newName: codeformuenster/kibana-oss-plugins
  newTag: "7.2.0-testing1"

patchesStrategicMerge:
- ./patches.yaml

configMapGenerator:
- name: kibana-kibana-config
  behavior: replace
  files:
  - kibana.yml=./config.yaml
