apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  # annotations:
  #   FIXME add something for cookie size, keycloak.. in ../base
spec:
  rules:
  - host: keycloak.example.com
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: http
  tls:
  - secretName: keycloak-tls
    hosts:
    - keycloak.example.com

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: keycloak-tls
spec:
  commonName: keycloak.example.com
