apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak
commonLabels:
  app.kubernetes.io/part-of: keycloak

resources:
- ./keycloak.yaml
- ./postgres.yaml
- ./oidcmapping-ClusterRole.yaml

images:
- name: jboss/keycloak
  newTag: 6.0.1
- name: postgres
  newTag: 11.5-alpine
- name: alpine
  newTag: 3.10

# secretGenerator:
# - name: keycloak-admin-user
#   env: ./secrets/keycloak-password-secret
# - name: postgres
#   env: ./secrets/postgres-password-secret
# 
# patchesStrategicMerge:
# - ./keycloak-ingress-patch.yaml
