apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gangway
commonLabels:
  app.kubernetes.io/part-of: gangway

resources:
- ./gangway.yaml

configMapGenerator:
- name: gangway
  files:
  - ./gangway-config.yaml

secretGenerator:
- name: session-security-key
  env: ./secrets/session-security-key
- name: client-secret
  env: ./secrets/client-secret
