apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealms.k8s.kiwigrid.com
spec:
  group: k8s.kiwigrid.com
  version: v1beta1
  scope: Cluster
  names:
    kind: KeycloakRealm
    singular: keycloakrealm
    plural: keycloakrealms
    shortNames: [ kcr ]
  additionalPrinterColumns:
  - name: KEYCLOAK
    type: string
    description: The name of the Keycloak.
    JSONPath: .spec.keycloak
  - name: REALM
    type: string
    description: The name of the realm.
    JSONPath: .spec.realm
  - name: TIMESTAMP
    type: string
    description: The timestamp of the realm.
    JSONPath: .status.timestamp
  - name: ERROR
    type: string
    description: The error of the realm.
    JSONPath: .status.error
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - realm
          properties:
            keycloak:
              description: 'Name of Keycloak to use, defaults to: keycloak'
              type: string
            realm:
              description: 'Name of realm to create'
              type: string
            roles:
              description: 'Realm roles to create if missing'
              type: array
              items:
                type: string
        status:
          type: object
          required:
          - timestamp
          properties:
            timestamp:
              type: string
            error:
              type: string