apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
- apiGroups:
  - k8s.kiwigrid.com
  resources:
  - keycloaks
  - keycloakrealms
  - keycloakclients
  verbs:
  - get
  - list
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloak-operator
subjects:
- kind: ServiceAccount
  name: keycloak-operator
  namespace: keycloak

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: micronaut
data:
  application-k8s.yaml: |-
    micronaut:
      metrics:
        export:
          prometheus:
            enabled: "true"
            step: PT5s
            descriptions: false
    endpoints:
      prometheus:
        enabled: "true"
    retry-rate: 60s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
  labels:
    app.kubernetes.io/name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak-operator
    spec:
      serviceAccountName: keycloak-operator
      containers:
      - name: keycloak-operator
        image: kiwigrid/keycloak-controller:1.0.0
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: metrics
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /endpoints/health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 2
          failureThreshold: 55
        livenessProbe:
          httpGet:
            path: /endpoints/health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 3
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms48m -Xmx48m -XX:MetaspaceSize=56m -XX:MaxMetaspaceSize=56m -XX:ReservedCodeCacheSize=8m -XX:CompressedClassSpaceSize=12m -XX:MaxDirectMemorySize=1m"
        - name: MICRONAUT_CONFIG_FILES
          value: /kiwigrid/application-k8s.yaml
        - name: GCP_LOGGING
          value: "true"
        # resources: FIXME
        volumeMounts:
        - name: micronaut
          mountPath: /kiwigrid/application-k8s.yaml
          subPath: application-k8s.yaml
      volumes:
      - name: micronaut
        configMap:
          name: micronaut
