apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/part-of: ingress-nginx

resources:
- ../cloud-generic
- ../cluster-wide

# FIXME add grafana dashboard as [custom resource](https://github.com/integr8ly/grafana-operator/blob/master/documentation/dashboards.md)
# FIXME add prometheus-servicemonitor
