apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app.kubernetes.io/name: minio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      # FIXME run as non-root
      containers:
      - name: minio
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: access
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secret
        ports:
        - name: s3
          containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          # initialDelaySeconds: 120
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          # initialDelaySeconds: 120
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - name: data 
          mountPath: "/data"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
