apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
commonLabels:
  app.kubernetes.io/part-of: cert-manager

resources:
- ./cert-manager.yaml
# - ./servicemonitor.yaml

# images:
# - name: quay.io/jetstack/cert-manager-controller
#   newTag: v0.9.0
# - name: quay.io/jetstack/cert-manager-webhook
#   newTag: v0.9.0
# - name: quay.io/jetstack/cert-manager-cainjector
#   newTag: v0.9.0
